/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yjy.apcs.rpc.server.report;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-07-05")
public class FundCapitalRpcService {

  public interface Iface {

    public TPaginationVo findPaginationGoodsOutList(TRequestReportVo requestReportVo) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void findPaginationGoodsOutList(TRequestReportVo requestReportVo, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public TPaginationVo findPaginationGoodsOutList(TRequestReportVo requestReportVo) throws org.apache.thrift.TException
    {
      send_findPaginationGoodsOutList(requestReportVo);
      return recv_findPaginationGoodsOutList();
    }

    public void send_findPaginationGoodsOutList(TRequestReportVo requestReportVo) throws org.apache.thrift.TException
    {
      findPaginationGoodsOutList_args args = new findPaginationGoodsOutList_args();
      args.setRequestReportVo(requestReportVo);
      sendBase("findPaginationGoodsOutList", args);
    }

    public TPaginationVo recv_findPaginationGoodsOutList() throws org.apache.thrift.TException
    {
      findPaginationGoodsOutList_result result = new findPaginationGoodsOutList_result();
      receiveBase(result, "findPaginationGoodsOutList");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "findPaginationGoodsOutList failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void findPaginationGoodsOutList(TRequestReportVo requestReportVo, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      findPaginationGoodsOutList_call method_call = new findPaginationGoodsOutList_call(requestReportVo, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class findPaginationGoodsOutList_call extends org.apache.thrift.async.TAsyncMethodCall {
      private TRequestReportVo requestReportVo;
      public findPaginationGoodsOutList_call(TRequestReportVo requestReportVo, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.requestReportVo = requestReportVo;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("findPaginationGoodsOutList", org.apache.thrift.protocol.TMessageType.CALL, 0));
        findPaginationGoodsOutList_args args = new findPaginationGoodsOutList_args();
        args.setRequestReportVo(requestReportVo);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public TPaginationVo getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_findPaginationGoodsOutList();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("findPaginationGoodsOutList", new findPaginationGoodsOutList());
      return processMap;
    }

    public static class findPaginationGoodsOutList<I extends Iface> extends org.apache.thrift.ProcessFunction<I, findPaginationGoodsOutList_args> {
      public findPaginationGoodsOutList() {
        super("findPaginationGoodsOutList");
      }

      public findPaginationGoodsOutList_args getEmptyArgsInstance() {
        return new findPaginationGoodsOutList_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public findPaginationGoodsOutList_result getResult(I iface, findPaginationGoodsOutList_args args) throws org.apache.thrift.TException {
        findPaginationGoodsOutList_result result = new findPaginationGoodsOutList_result();
        result.success = iface.findPaginationGoodsOutList(args.requestReportVo);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("findPaginationGoodsOutList", new findPaginationGoodsOutList());
      return processMap;
    }

    public static class findPaginationGoodsOutList<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, findPaginationGoodsOutList_args, TPaginationVo> {
      public findPaginationGoodsOutList() {
        super("findPaginationGoodsOutList");
      }

      public findPaginationGoodsOutList_args getEmptyArgsInstance() {
        return new findPaginationGoodsOutList_args();
      }

      public AsyncMethodCallback<TPaginationVo> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<TPaginationVo>() { 
          public void onComplete(TPaginationVo o) {
            findPaginationGoodsOutList_result result = new findPaginationGoodsOutList_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            findPaginationGoodsOutList_result result = new findPaginationGoodsOutList_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, findPaginationGoodsOutList_args args, org.apache.thrift.async.AsyncMethodCallback<TPaginationVo> resultHandler) throws TException {
        iface.findPaginationGoodsOutList(args.requestReportVo,resultHandler);
      }
    }

  }

  public static class findPaginationGoodsOutList_args implements org.apache.thrift.TBase<findPaginationGoodsOutList_args, findPaginationGoodsOutList_args._Fields>, java.io.Serializable, Cloneable, Comparable<findPaginationGoodsOutList_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("findPaginationGoodsOutList_args");

    private static final org.apache.thrift.protocol.TField REQUEST_REPORT_VO_FIELD_DESC = new org.apache.thrift.protocol.TField("requestReportVo", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new findPaginationGoodsOutList_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new findPaginationGoodsOutList_argsTupleSchemeFactory());
    }

    public TRequestReportVo requestReportVo; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      REQUEST_REPORT_VO((short)1, "requestReportVo");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // REQUEST_REPORT_VO
            return REQUEST_REPORT_VO;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.REQUEST_REPORT_VO, new org.apache.thrift.meta_data.FieldMetaData("requestReportVo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TRequestReportVo.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(findPaginationGoodsOutList_args.class, metaDataMap);
    }

    public findPaginationGoodsOutList_args() {
    }

    public findPaginationGoodsOutList_args(
      TRequestReportVo requestReportVo)
    {
      this();
      this.requestReportVo = requestReportVo;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public findPaginationGoodsOutList_args(findPaginationGoodsOutList_args other) {
      if (other.isSetRequestReportVo()) {
        this.requestReportVo = new TRequestReportVo(other.requestReportVo);
      }
    }

    public findPaginationGoodsOutList_args deepCopy() {
      return new findPaginationGoodsOutList_args(this);
    }

    @Override
    public void clear() {
      this.requestReportVo = null;
    }

    public TRequestReportVo getRequestReportVo() {
      return this.requestReportVo;
    }

    public findPaginationGoodsOutList_args setRequestReportVo(TRequestReportVo requestReportVo) {
      this.requestReportVo = requestReportVo;
      return this;
    }

    public void unsetRequestReportVo() {
      this.requestReportVo = null;
    }

    /** Returns true if field requestReportVo is set (has been assigned a value) and false otherwise */
    public boolean isSetRequestReportVo() {
      return this.requestReportVo != null;
    }

    public void setRequestReportVoIsSet(boolean value) {
      if (!value) {
        this.requestReportVo = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case REQUEST_REPORT_VO:
        if (value == null) {
          unsetRequestReportVo();
        } else {
          setRequestReportVo((TRequestReportVo)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case REQUEST_REPORT_VO:
        return getRequestReportVo();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case REQUEST_REPORT_VO:
        return isSetRequestReportVo();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof findPaginationGoodsOutList_args)
        return this.equals((findPaginationGoodsOutList_args)that);
      return false;
    }

    public boolean equals(findPaginationGoodsOutList_args that) {
      if (that == null)
        return false;

      boolean this_present_requestReportVo = true && this.isSetRequestReportVo();
      boolean that_present_requestReportVo = true && that.isSetRequestReportVo();
      if (this_present_requestReportVo || that_present_requestReportVo) {
        if (!(this_present_requestReportVo && that_present_requestReportVo))
          return false;
        if (!this.requestReportVo.equals(that.requestReportVo))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_requestReportVo = true && (isSetRequestReportVo());
      list.add(present_requestReportVo);
      if (present_requestReportVo)
        list.add(requestReportVo);

      return list.hashCode();
    }

    @Override
    public int compareTo(findPaginationGoodsOutList_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetRequestReportVo()).compareTo(other.isSetRequestReportVo());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetRequestReportVo()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requestReportVo, other.requestReportVo);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("findPaginationGoodsOutList_args(");
      boolean first = true;

      sb.append("requestReportVo:");
      if (this.requestReportVo == null) {
        sb.append("null");
      } else {
        sb.append(this.requestReportVo);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (requestReportVo != null) {
        requestReportVo.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class findPaginationGoodsOutList_argsStandardSchemeFactory implements SchemeFactory {
      public findPaginationGoodsOutList_argsStandardScheme getScheme() {
        return new findPaginationGoodsOutList_argsStandardScheme();
      }
    }

    private static class findPaginationGoodsOutList_argsStandardScheme extends StandardScheme<findPaginationGoodsOutList_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, findPaginationGoodsOutList_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // REQUEST_REPORT_VO
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.requestReportVo = new TRequestReportVo();
                struct.requestReportVo.read(iprot);
                struct.setRequestReportVoIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, findPaginationGoodsOutList_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.requestReportVo != null) {
          oprot.writeFieldBegin(REQUEST_REPORT_VO_FIELD_DESC);
          struct.requestReportVo.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class findPaginationGoodsOutList_argsTupleSchemeFactory implements SchemeFactory {
      public findPaginationGoodsOutList_argsTupleScheme getScheme() {
        return new findPaginationGoodsOutList_argsTupleScheme();
      }
    }

    private static class findPaginationGoodsOutList_argsTupleScheme extends TupleScheme<findPaginationGoodsOutList_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, findPaginationGoodsOutList_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetRequestReportVo()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetRequestReportVo()) {
          struct.requestReportVo.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, findPaginationGoodsOutList_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.requestReportVo = new TRequestReportVo();
          struct.requestReportVo.read(iprot);
          struct.setRequestReportVoIsSet(true);
        }
      }
    }

  }

  public static class findPaginationGoodsOutList_result implements org.apache.thrift.TBase<findPaginationGoodsOutList_result, findPaginationGoodsOutList_result._Fields>, java.io.Serializable, Cloneable, Comparable<findPaginationGoodsOutList_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("findPaginationGoodsOutList_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new findPaginationGoodsOutList_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new findPaginationGoodsOutList_resultTupleSchemeFactory());
    }

    public TPaginationVo success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TPaginationVo.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(findPaginationGoodsOutList_result.class, metaDataMap);
    }

    public findPaginationGoodsOutList_result() {
    }

    public findPaginationGoodsOutList_result(
      TPaginationVo success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public findPaginationGoodsOutList_result(findPaginationGoodsOutList_result other) {
      if (other.isSetSuccess()) {
        this.success = new TPaginationVo(other.success);
      }
    }

    public findPaginationGoodsOutList_result deepCopy() {
      return new findPaginationGoodsOutList_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public TPaginationVo getSuccess() {
      return this.success;
    }

    public findPaginationGoodsOutList_result setSuccess(TPaginationVo success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((TPaginationVo)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof findPaginationGoodsOutList_result)
        return this.equals((findPaginationGoodsOutList_result)that);
      return false;
    }

    public boolean equals(findPaginationGoodsOutList_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(findPaginationGoodsOutList_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("findPaginationGoodsOutList_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class findPaginationGoodsOutList_resultStandardSchemeFactory implements SchemeFactory {
      public findPaginationGoodsOutList_resultStandardScheme getScheme() {
        return new findPaginationGoodsOutList_resultStandardScheme();
      }
    }

    private static class findPaginationGoodsOutList_resultStandardScheme extends StandardScheme<findPaginationGoodsOutList_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, findPaginationGoodsOutList_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new TPaginationVo();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, findPaginationGoodsOutList_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class findPaginationGoodsOutList_resultTupleSchemeFactory implements SchemeFactory {
      public findPaginationGoodsOutList_resultTupleScheme getScheme() {
        return new findPaginationGoodsOutList_resultTupleScheme();
      }
    }

    private static class findPaginationGoodsOutList_resultTupleScheme extends TupleScheme<findPaginationGoodsOutList_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, findPaginationGoodsOutList_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, findPaginationGoodsOutList_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = new TPaginationVo();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
